services:
  - type: web
    name: triathlon-health-tracker-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_o4zNmfnPe1RF@ep-calm-queen-adcu5qyx-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    healthCheckPath: /api/health

